apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.30.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: devpi
  name: devpi
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: devpi
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.30.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/devstack-default: "true"
        io.kompose.service: devpi
    spec:
      containers:
        - image: edxops/devpi:latest
          name: edx.devstack.devpi
          ports:
            - containerPort: 3141
              hostPort: 3141
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /data
              name: devpi-data
      hostname: devpi.devstack.edx
      restartPolicy: Always
      volumes:
        - name: devpi-data
          persistentVolumeClaim:
            claimName: devpi-data
status: {}
