apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.30.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: discovery
  name: discovery
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: discovery
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.30.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/devstack-default: "true"
        io.kompose.service: discovery
    spec:
      containers:
        - args:
            - bash
            - -c
            - source /edx/app/discovery/discovery_env && while true; do python /edx/app/discovery/discovery/manage.py runserver 0.0.0.0:18381; sleep 2; done
          env:
            - name: DB_MIGRATION_HOST
              value: edx.devstack.mysql57
            - name: DJANGO_WATCHMAN_TIMEOUT
              value: "30"
            - name: ENABLE_DJANGO_TOOLBAR
              value: "1"
            - name: TEST_ELASTICSEARCH_URL
              value: edx.devstack.elasticsearch710
          image: edxops/discovery-dev:latest
          name: edx.devstack.discovery
          ports:
            - containerPort: 18381
              hostPort: 18381
              protocol: TCP
          resources: {}
          stdin: true
          tty: true
          volumeMounts:
            - mountPath: /edx/var/discovery
              name: discovery-assets
            - mountPath: /edx/etc/discovery.yml
              name: discovery-claim1
      hostname: discovery.devstack.edx
      restartPolicy: Always
      volumes:
        - name: discovery-assets
          persistentVolumeClaim:
            claimName: discovery-assets
        - name: discovery-claim1
          persistentVolumeClaim:
            claimName: discovery-claim1
status: {}
