apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.30.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: forum
  name: forum
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: forum
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.30.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/devstack-default: "true"
        io.kompose.service: forum
    spec:
      containers:
        - args:
            - bash
            - -c
            - source /edx/app/forum/ruby_env && source /edx/app/forum/devstack_forum_env && cd /edx/app/forum/cs_comments_service && bundle install && while true; do ./bin/unicorn -c config/unicorn_tcp.rb -I .; sleep 2; done
          image: edxops/forum:latest
          name: edx.devstack.forum
          ports:
            - containerPort: 4567
              hostPort: 44567
              protocol: TCP
          resources: {}
          stdin: true
          tty: true
      hostname: forum.devstack.edx
      restartPolicy: Always
status: {}
