apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.30.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: registrar
  name: registrar
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: registrar
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.30.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/devstack-default: "true"
        io.kompose.service: registrar
    spec:
      containers:
        - args:
            - bash
            - -c
            - while true; do python /edx/app/registrar/manage.py runserver 0.0.0.0:18734; sleep 2; done
          env:
            - name: ANALYTICS_DASHBOARD_CFG
              value: /edx/etc/registrar.yml
            - name: CELERY_ALWAYS_EAGER
              value: "false"
            - name: CELERY_BROKER_HOSTNAME
              value: edx.devstack.redis:6379
            - name: CELERY_BROKER_PASSWORD
              value: password
            - name: CELERY_BROKER_TRANSPORT
              value: redis
            - name: CELERY_BROKER_VHOST
              value: "10"
            - name: DB_HOST
              value: edx.devstack.mysql57
            - name: DB_NAME
              value: registrar
            - name: DB_PASSWORD
              value: password
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: registrar001
            - name: DJANGO_SETTINGS_MODULE
              value: registrar.settings.devstack
            - name: DJANGO_WATCHMAN_TIMEOUT
              value: "30"
            - name: LMS_HOST
              value: http://localhost:18000
            - name: MEMCACHE_HOST
              value: edx.devstack.memcached
          image: edxops/registrar-dev:latest
          name: edx.devstack.registrar
          ports:
            - containerPort: 18734
              hostPort: 18734
              protocol: TCP
          resources: {}
          stdin: true
          tty: true
          volumeMounts:
            - mountPath: /edx/var/registrar
              name: registrar-claim0
            - mountPath: /edx/etc/registrar.yml
              name: registrar-claim1
          workingDir: /edx/app/registrar
      hostname: registrar.devstack.edx
      restartPolicy: Always
      volumes:
        - name: registrar-claim0
          persistentVolumeClaim:
            claimName: registrar-claim0
        - name: registrar-claim1
          persistentVolumeClaim:
            claimName: registrar-claim1
status: {}
